version: '2.1'

services:
  postgres:
    image: docker.io/postgres:10
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      POSTGRES_USER: passwordpusher_user
      POSTGRES_PASSWORD: passwordpusher_passwd
      POSTGRES_DB: passwordpusher_db

  passwordpusher:
    image: skf-secrets:latest
    ports:
      - "127.0.0.1:5100:5100"
    depends_on:
      - postgres
